[package]
name = "ushallblog"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ushallblog"
path = "src/main.rs"

[dependencies]
minify-html-onepass = "0.16.4"
pulldown-cmark = { version = "0.13", features = ["simd"] }
sailfish = "0.9.1"
walkdir = "2.5.0"
