[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
pulldown-cmark = { version = "0.9", features = ["simd"] }
walkdir = "2.5.0"
